### ISSUE TITLE
Absinthe Schema Error when compiling the app

### ISSUE THREAD

**Issue by jhefreyzz** [MatthieuSegret/yummy-phoenix-graphql#5]
Elixir v. 7
Erlang v. 20

I got compilation error when trying to run mix.phx.server
== Compilation error in file lib/yummy_web/schema.ex ==
** (Absinthe.Schema.Error) Invalid schema:
Elixir.YummyWeb.Schema:0: The root query type must be implemented and be a of type Object

**Comment by MatthieuSegret** [comment]
Hello, I think the Absinthe version I use is not compatible with Elixir 1.7. I was planning to work on the project in 1.7. But you have to use 1.6 in the meantime.

**Comment by jhefreyzz** [comment]
I see because of version incompatibility.
